[package]
name = "schema"
version = "0.1.0"
edition = "2024"

[dependencies]
kademlia = { version = "0.1.0", path = "../kademlia", features = ["minicbor"] }
minicbor = { version = "2.1.3", features = ["alloc", "std", "derive"] }
sha2 = "0.10.9"

[dev-dependencies]
expect-test = "1.5.1"
