[package]
name = "kademlia"
version = "0.1.0"
edition = "2024"

[dependencies]
expect-test = "1.5.1"
ringbuffer = "0.16.0"
sha2 = { version = "0.10.9", features = ["asm", "asm-aarch64"] }
thiserror = "2.0.16"
